name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull dssgx/hydroapp:latest
    - name: Delete Old docker container
      run: sudo docker rm -f hydroapp-container || true
    - name: Run Docker Container
      run: sudo docker run -td -p 80:5000 --name hydroapp-container dssgx/hydroapp
